### ISSUE TITLE
Please fix this issues

### ISSUE THREAD

**Issue by Mashpy** [NarayanChakraborty/NSTUBlood#1]
১।  what is blood এবং এর নিচে ফন্ট সাইজ বাড়াও। অনেক কষ্ট করে পড়তে হচ্ছে। আর এইগুলা বোল্ড দিস কেন? এই পেজে antigen এর বামদিকে blood group এই টা কোন স্পেস নাই। এই পেজেই সবচেয়ে নীচে antibodies are in the plasma এর নীচে স্পেস হবে। না হলে প্যাডিং বাড়ায়া দাও। 

২। blood donation এ are u capable of giving blood এই অংশে e. have no active vp;d symptoms এর নীচে নামা যায় না। এখানে স্ক্রলিং এ সমস্যা আছে।

৩। precautions অংশে Marriage নামে বাটন দিস। এর উপরে একটু স্পেস দিবা না? আর মেরিজে ক্লিক দিলাম। ঐখানে দেখি পুরাই সমস্যা। তুমি এক্সসেপশন হ্যান্ডেলিং কর নাই। আমি আমার নাম লিখতেছি...গার্লফ্রেন্ড এর নাম লিখি নাই। এখন ছবিটাতে ক্লিক দিলে দেখানো উচিত ছিল ভাই আপনি তো আরেকজনের নাম লিখেন নাই। কিন্তু আসতেছে mashpy your marriage is compatable !! আর যেই ছবিটা দিস ঐটাতে স্ট্যাটিক...ঐটা ছোট ডিভাইসে খুব বাজে দেখাচ্ছে। তোমার উচিত ছিল তোমার ডিভাইস ছাড়াও অন্য ডিভাইসে চেক করা। আমি NSTUinfo কমপক্ষে ১০০ বার চেক করছি। believe it or not. ২ মাস এমনি এমনি লাগে নাই।

৪। ব্লাড account এ ক্লিক দিসি। আমি স্ক্রলিং করতে পারতেছি না। নীচে যেতে পারতেছি না।

৫। পুরা এপ্লিকেশনে ২ activity তে ব্যাকগ্রাউন্ডে নীল আছে। এই নীলটাকে আরেকটু হালকা কর। চোখে লাগে।

**Comment by NarayanChakraborty** [comment]
Thanks vi... i will

**Comment by Mashpy** [comment]
thanks. i have closed the issue.
